pages/urls.py
from django.conf.urls import url
from . import views

app_name = 'pages'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^about/$', views.about, name='about'),
    url(r'^(?P<slug>[-\w]+)/$', views.category_detail, name='detail'),
    url(r'^category/new/$', views.category_create, name='create'),
    url(r'^(?P<slug>[-\w]+)/page/new/$', views.page_create, name='page_create')
]

pyread/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from pages import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^read/', include('pages.urls')),
    url(r'^users/', include('users.urls')),
    url(r'^$', views.index, name='root'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

users/urls.py
from django.conf.urls import url
from . import views

app_name = 'users'
urlpatterns = [
    url(r'^register/$', views.register, name='register'),
    url(r'^login/$', views.user_login, name='login'),
    url(r'^logout/$', views.user_logout, name='logout')
]

pages/models.py
from django.db import models
from django.utils.text import slugify
from django.core.urlresolvers import reverse
class Category(models.Model):
    name = models.CharField(max_length=120, unique=True, db_index=True)
    views = models.PositiveIntegerField(default=0)
    likes = models.PositiveIntegerField(default=0)
    slug = models.SlugField(unique=True, db_index=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = 'categories'
        ordering = ('name',)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(Category, self).save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('pages:detail', args=[self.slug])

class Page(models.Model):
    category = models.ForeignKey(Category, related_name='pages')
    title = models.CharField(max_length=120)
    url = models.URLField()
    views = models.PositiveIntegerField(default=0)

    def __str__(self):
        return self.title

    class Meta:
        ordering = ('title',)

users/models.py
from django.db import models
from django.contrib.auth.models import User
from django.dispatch import receiver
from django.db.models.signals import post_save, pre_delete, pre_save

class Profile(models.Model):
    user = models.OneToOneField(User)

    website = models.URLField(blank=True)
    image = models.ImageField(upload_to="profileimages", blank=True)

    def __str__(self):
        return self.user.username

    def save(self, *args, **kwargs):
        try:
            this = Profile.objects.get(pk=self.pk)
            if this.image != self.image:
                this.image.delete(save=False)
        except Profile.DoesNotExist:
            pass
        super(Profile, self).save(*args, **kwargs)

@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)

@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()

@receiver(pre_delete, sender=Profile)
def profile_delete(sender, instance, **kwargs):
    # Pass false so FileField doesn't save the model.
    instance.image.delete(False)

pages/forms.py
from django import forms
from .models import Category, Page


class CategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = ('name',)
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control'}),
        }
        help_texts = {
            'name': 'Please enter Category name',
        }


class PageForm(forms.ModelForm):
    class Meta:
        model = Page
        fields = ('title', 'url')
        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control'}),
            'url': forms.TextInput(attrs={'class': 'form-control'})
        }
        help_texts = {
            'title': 'Please enter title of the page',
            'url': 'Please enter the URL of the page'
        }

    def clean_url(self):
        url = self.cleaned_data.get('url')
        if url and not url.startswith('http://'):
            url = 'http://' + url
        return url

users/forms.py
from django import forms
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from .models import Profile

class UserForm(forms.ModelForm):
    confirm_password = forms.CharField()
    password = forms.CharField()

    def __init__(self, *args, **kwargs):
        super(UserForm, self).__init__(*args, **kwargs)
        for field in self.visible_fields():
            field.field.widget.attrs['class'] = 'form-control'

    class Meta:
        model = User
        fields = ('username', 'email', 'password', 'confirm_password')

    def clean(self):
        if self.cleaned_data['password'] != self.cleaned_data['confirm_password']:
            raise ValidationError("Passwords didn't match.")
        return self.cleaned_data

class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ('website', 'image')
        widgets = {
            'website': forms.TextInput(attrs={'class': 'form-control'})
        }

class LoginForm(forms.Form):
    username = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control'}))

pages/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from .models import Category, Page
from .forms import CategoryForm, PageForm


def index(request):
    categories = Category.objects.order_by("-likes")[:5]
    most_viewed_pages = Page.objects.order_by("-views")[:5]
    return render(request, 'pages/index.html', {'categories': categories,
                                                'pages': most_viewed_pages})


def about(request):
    return render(request, 'pages/about.html')

def category_detail(request, slug):
    category = get_object_or_404(Category, slug=slug)
    pages = category.pages.all()
    return render(request, 'pages/category/detail.html', {'category': category, 'pages': pages})

@login_required
def category_create(request):
    if request.method == 'POST':
        form = CategoryForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('root')
        else:
            print(form.errors)
    else:
        form = CategoryForm()
    return render(request, 'pages/category/create.html', {'form': form})

@login_required
def page_create(request, slug):
    category = get_object_or_404(Category, slug=slug)
    if request.method == 'POST':
        form = PageForm(request.POST)
        if form.is_valid():
            page = form.save(commit=False)
            page.category = category
            page.save()
            return redirect(category)
        else:
            print(form.errors)
    else:
        form = PageForm()
    return render(request, 'pages/create.html', {'form': form, 'category': category})

users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from .forms import UserForm, ProfileForm, LoginForm


def register(request):
    if request.method == 'POST':
        user_form = UserForm(data=request.POST)
        if user_form.is_valid():
            user = user_form.save()
            user.set_password(user_form.cleaned_data['password'])
            user.save()
            profile_form = ProfileForm(data=request.POST, files=request.FILES, instance=user.profile)
            if profile_form.is_valid():
                profile_form.save()
                if user.is_active:
                    login(request, user)
                return redirect('root')
    else:
        user_form = UserForm()
        profile_form = ProfileForm()
    return render(request, 'users/register.html', {'user_form': user_form, 'profile_form': profile_form})

def user_login(request):
    logout(request)
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            user = authenticate(username=form.cleaned_data['username'], password=form.cleaned_data['password'])
            if user:
                if user.is_active:
                    login(request, user)
                    return redirect('root')
            else:
                form.add_error('username', 'Does not exist')
    else:
        form = LoginForm()
    return render(request, 'users/login.html', {'form': form})

@login_required
def user_logout(request):
    logout(request)
    return redirect('root')

pages/templates/pages/about.html
{% extends "pages/base.html" %}
{% block title %}
  About | {{ block.super }}
{% endblock %}

{% block content %}
  <h1>Here is about page</h1>
{% endblock %}

pages/templates/pages/base.html
<!DOCTYPE html>
{% load static %}
{% load pages_tags %}
<html>
  <head>
    <meta charset="utf-8" />
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>{% block title %}PyRead{% endblock %}</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.5/css/bootstrap.min.css" integrity="sha384-AysaV+vQoT3kOAXZkl02PThvDr8HYKPZhNT5h/CXfBThSRXQ6jW5DO2ekP5ViFdi" crossorigin="anonymous">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
  </head>
  <body>
    {% include 'pages/navbar.html'%}
    <div class="container-fluid">

      <div class="row">
        <div class="col-md-2">

          {% block sidebar %}
          {% category_list category %}
          {% endblock %}
        </div>
        <div class="col-md-10">
          {% block content %}{% endblock %}
        </div>

      </div>
    </div>


    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.5/js/bootstrap.min.js" integrity="sha384-BLiI7JTZm+JWlgKa0M0kGRpJbF2J8q+qreVrKBC47e3K6BW78kGLrCkeRX6I9RoK" crossorigin="anonymous"></script>
    <script src="{% static 'pages/js/main.js' %}">
    </script>
  </body>
</html>

pages/templates/pages/categories.html
<div class="list-group">
  {% if categories %}
  {% for c in categories %}
    {% if c == active_cat %}
        <strong>
        <a class="list-group-item" href="{% url 'pages:detail' c.slug %}">{{ c.name }}</a>
        </strong>
    {% else %}
      <a class="list-group-item" href="{% url 'pages:detail' c.slug %}">{{ c.name }}</a>
    {% endif %}
  {% endfor %}
  {% else %}
  <strong>There are no categories present.</strong>
  {% endif %}
</div>

pages/templates/pages/category/create.html
{% extends "pages/base.html" %}

{% block title %}
  Add Category | {{ block.super }}
{% endblock %}

{% block content %}
<h1>Create Category</h1>
<div>
  <form class="col-md-6" id="category_form" method="post" action="" novalidate>
    {% csrf_token %}
    {% for field in form %}
    <div class="form-group">
      {{ field.help_text }}<br>
      {{ field }}
      {{ field.errors }}
    </div>
    {% endfor %}
    <input class="btn btn-primary" type="submit" name="submit" value="Create Category" />
  </form>
</div>

{% endblock %}

pages/templates/pages/category/detail.html
{% extends "pages/base.html" %}

{% block title %}
  {{ category.title }}
{% endblock %}

{% block content %}
<div>
  <h1>{{ category.name }}</h1>
  {% if pages %}
    <ul>
      {% for page in pages %}
        <li><a href="{{ page.url }}">{{ page.title }}</a></li>
      {% endfor %}
    </ul>
  {% else %}
    <strong>No pages currently in category.</strong>
  {% endif %}
</div>
<div >
  <a href="{% url 'pages:page_create' category.slug %}"><i class="fa fa-plus-circle"></i> Add Page</a>
</div>
{% endblock %}

pages/templates/pages/create.html
{% extends "pages/base.html" %}

{% block title %}
  Add Page | {{ block.super }}
{% endblock %}

{% block content %}
  <h1>Add new Page</h1>
  <div>
    <form class="col-md-6" id="page_form" method="post" action="" novalidate>
      {% csrf_token %}
      {% for field in form %}
      <div class="form-group">
        {{ field.help_text }}<br>
        {{ field }}
        {{ field.errors }}
      </div>
      {% endfor %}

      <input class="btn btn-primary" type="submit" name="submit" value="Create Page" />
    </form>
  </div>
{% endblock %}

pages/templates/pages/detail.html
{% extends "pages/base.html" %}

{% block title %}
  {{ category.title }}
{% endblock %}

{% block content %}
<div>
  <h1>{{ category.name }}</h1>
  {% if pages %}
    <ul>
      {% for page in pages %}
        <li><a href="{{ page.url }}">{{ page.title }}</a></li>
      {% endfor %}
    </ul>
  {% else %}
    <strong>No pages currently in category.</strong>
  {% endif %}
</div>
<div >
  <a href="{% url 'root' %}">Back to index</a>
</div>
{% endblock %}

pages/templates/pages/index.html
{% extends "pages/base.html" %}
{% load static %}
{% block content %}

<div class="container">
<div class="jumbotron">
  <h1>Welcome</h1>
  <p>We're glad to see you, {% if user.is_authenticated %}{{ user.username }}{% else %}bro{% endif %}!</p>
</div>
  <div class="row">
    <div class="col-lg-6">
      <h1>Most Liked Categories</h1>
      {% if categories %}
      <div class="list-group">
        {% for category in categories %}
        <a class="list-group-item" href="{{ category.get_absolute_url }}">{{ category.name }}</a>
        {% endfor %}
      </div>
      {% else %}
      <strong>There are no categories present.</strong>
      {% endif %}
    </div>
    <div class="col-lg-6">
        <h1>Most Viewed Links</h1>
        {% if pages %}
        <div class="list-group">
          {% for page in pages %}
          <a class="list-group-item" href="{{ page.url }}">{{ page.title }}</a>
          {% endfor %}
        {% else %}
        <strong>There are no pages present.</strong>
        {% endif %}
  </div>
  </div>
</div>
{% endblock %}

pages/templates/pages/navbar.html
{% load static %}
<nav class="navbar navbar-dark bg-inverse">
  <button class="navbar-toggler hidden-lg-up" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation"></button>
  <div class="collapse navbar-toggleable-md" id="navbarResponsive">
    <a class="navbar-brand" href="{% url 'root'%}">
      <img src="{% static 'pages/images/logo.png' %}" width="30" heigh="30" alt="Logo" />
      PyRead
    </a>
    <ul class="nav navbar-nav">
      <li class="nav-item">
        <a class="nav-link" href="{% url 'pages:about' %}"><i class="fa fa-info-circle" aria-hidden="true"></i> About</a>
      </li>
    </ul>
    <ul class="nav navbar-nav float-lg-right">
      {% if user.is_authenticated %}
      <li class="nav-item">
        <a class="nav-link" href="{% url 'pages:create' %}"><i class="fa fa-plus-circle" aria-hidden="true"></i> Add New Category</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'users:logout' %}"><i class="fa fa-sign-out" aria-hidden="true"></i> Logout</a>
      </li>
      {% else %}
      <li class="nav-item">
        <a class="nav-link" href="{% url 'users:register' %}"><i class="fa fa-pencil" aria-hidden="true"></i> Register</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'users:login' %}"><i class="fa fa-sign-in" aria-hidden="true"></i> Login</a>
      </li>
      {% endif %}
    </ul>
  </div>
</nav>

users/templates/users/login.html
{% extends "pages/base.html" %}
{% block title %}
  Register | {{ block.super }}
{% endblock %}

{% block content %}
<div class="row">
  <h1>Log In</h1>
  <div class="col-md-6">

    <form class="" action="" method="post" enctype="multipart/form-data">
      {% csrf_token %}
      {% for field in form %}
      <div class="form-group ">
        {{ field.label_tag}} {{ field }}
        {% if field.errors %}
        <div>{{ field.errors }}</div>
        {% endif %}
      </div>
      {% endfor %}
      <input type="submit" class="btn btn-primary" value="Login">
    </form>
  </div>
</div>
{% endblock %}

users/templates/users/register.html
{% extends "pages/base.html" %}
{% block title %}
  Register | {{ block.super }}
{% endblock %}

{% block content %}
<div class="row">
  <h1>Register here</h1>
  <div class="col-md-6">

    <form class="" action="" method="post" enctype="multipart/form-data">
      {% if form.errors %}
        {{ form.errors }}
      {% endif %}
      {% csrf_token %}
      {% for field in user_form %}
      <div class="form-group ">
        {{ field.label_tag}} {{ field }}
        {% if field.errors %}
        <div>{{ field.errors }}</div>
        {% endif %}
      </div>
      {% endfor %}
      {% for field in profile_form %}
      <div class="form-group ">
        {{ field.label_tag}} {{field}}
        {% if field.errors %}
        <div>{{ field.errors }}</div>
        {% endif %}
      </div>
      {% endfor %}
      <input type="submit" class="btn btn-primary" value="Register">
    </form>
  </div>
</div>
{% endblock %}